OPENCV_DIR=""
LIB_DIR=""
CUDA_LIB_DIR= 
CUDNN_LIB_DIR= 

BUILD_DIR=out
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. -DPADDLE_LIB=${LIB_DIR} -DWITH_MKL=ON -DWITH_GPU=OFF -DWITH_STATIC_LIB=OFF -DWITH_TENSORRT=OFF -DOPENCV_DIR=${OPENCV_DIR} -DOpenCV_DIR=${OPENCV_DIR}

make -j
